version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    restart: always
    stdin_open: true
    volumes:
      - '.:/src'
    tty: true
    env_file:
      - .env.local
    entrypoint: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
#    command: gunicorn --bind 0.0.0.0:5000 --timeout 480 --access-logfile '-' wsgi:application --preload
  db:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env.local
    volumes:
      - mc_menu_db_data:/var/lib/postgresql/data

volumes:
    mc_menu_db_data:
