CATEGORY_COLUMN_NAME = "Category"

EXTENSIONS = ["csv"]

IMPORT_CATEGORY_NAME = "Category"
IMPORT_ITEM_NAME = "Item"
IMPORT_SERVING_SIZE_NAME = "Serving Size"
IMPORT_CALORIES_NAME = "Calories"
IMPORT_CALORIES_FROM_FAT_NAME = "Calories from Fat"
IMPORT_TOTAL_FAT_NAME = "TotalFat"
IMPORT_TOTAL_FAT_DAILY_VALUE_NAME = "Total Fat (% Daily Value)"
IMPORT_SATURATED_FAT_NAME = "Saturated Fat"
IMPORT_SATURATED_FAT_DAILY_VALUE_NAME = "Saturated Fat (% Daily Value)"
IMPORT_TRANS_FAT_NAME = "Trans Fat"
IMPORT_CHOLESTEROL_NAME = "Cholesterol"
IMPORT_CHOLESTEROL_DAILY_VALUE_NAME = "Cholesterol (% Daily Value)"
IMPORT_SODIUM_NAME = "Sodium"
IMPORT_SODIUM_DAILY_VALUE_NAME = "Sodium (% Daily Value)"
IMPORT_CARBOHYDRATES_NAME = "Carbohydrates"
IMPORT_CARBOHYDRATES_DAILY_VALUE_NAME = "Carbohydrates (% Daily Value)"
IMPORT_DIETARY_FIBER_NAME = "Dietary Fiber"
IMPORT_DIETARY_FIBER_DAILY_VALUE_NAME = "Dietary Fiber (% Daily Value)"
IMPORT_SUGARS_NAME = "Sugars"
IMPORT_PROTEIN_NAME = "Protein"
IMPORT_VITAMIN_A_DAILY_VALUE_NAME = "Vitamin A (% Daily Value)"
IMPORT_VITAMIN_C_DAILY_VALUE_NAME = "Vitamin C (% Daily Value)"
IMPORT_CALCIUM_NAME = "Calcium (% Daily Value)"
IMPORT_IRON_DAILY_VALUE_NAME = "Iron (% Daily Value)"


FILE_COLUMNS = [
    IMPORT_CATEGORY_NAME,
    IMPORT_ITEM_NAME,
    IMPORT_SERVING_SIZE_NAME,
    IMPORT_CALORIES_NAME,
    IMPORT_CALORIES_FROM_FAT_NAME,
    IMPORT_TOTAL_FAT_NAME,
    IMPORT_TOTAL_FAT_DAILY_VALUE_NAME,
    IMPORT_SATURATED_FAT_NAME,
    IMPORT_SATURATED_FAT_DAILY_VALUE_NAME,
    IMPORT_TRANS_FAT_NAME,
    IMPORT_CHOLESTEROL_NAME,
    IMPORT_CHOLESTEROL_DAILY_VALUE_NAME,
    IMPORT_SODIUM_NAME,
    IMPORT_SODIUM_DAILY_VALUE_NAME,
    IMPORT_CARBOHYDRATES_NAME,
    IMPORT_CARBOHYDRATES_DAILY_VALUE_NAME,
    IMPORT_DIETARY_FIBER_NAME,
    IMPORT_DIETARY_FIBER_DAILY_VALUE_NAME,
    IMPORT_SUGARS_NAME,
    IMPORT_PROTEIN_NAME,
    IMPORT_VITAMIN_A_DAILY_VALUE_NAME,
    IMPORT_VITAMIN_C_DAILY_VALUE_NAME,
    IMPORT_CALCIUM_NAME,
    IMPORT_IRON_DAILY_VALUE_NAME,
]

COLUMNS_NAMES_MAP = {
    IMPORT_CATEGORY_NAME: "category",
    IMPORT_ITEM_NAME: "name",
    IMPORT_SERVING_SIZE_NAME: "serving_size",
    IMPORT_CALORIES_NAME: "calories",
    IMPORT_CALORIES_FROM_FAT_NAME: "calories_from_fat",
    IMPORT_TOTAL_FAT_NAME: "total_fat",
    IMPORT_TOTAL_FAT_DAILY_VALUE_NAME: "total_fat_daily_value",
    IMPORT_SATURATED_FAT_NAME: "saturated_fat",
    IMPORT_SATURATED_FAT_DAILY_VALUE_NAME: "saturated_fat_daily_value",
    IMPORT_TRANS_FAT_NAME: "trans_fat",
    IMPORT_CHOLESTEROL_NAME: "cholesterol",
    IMPORT_CHOLESTEROL_DAILY_VALUE_NAME: "cholesterol_daily_value",
    IMPORT_SODIUM_NAME: "sodium",
    IMPORT_SODIUM_DAILY_VALUE_NAME: "sodium_daily_value",
    IMPORT_CARBOHYDRATES_NAME: "carbohydrates",
    IMPORT_CARBOHYDRATES_DAILY_VALUE_NAME: "carbohydrates_daily_value",
    IMPORT_DIETARY_FIBER_NAME: "dietary_fiber",
    IMPORT_DIETARY_FIBER_DAILY_VALUE_NAME: "dietary_fiber_daily_value",
    IMPORT_SUGARS_NAME: "sugars",
    IMPORT_PROTEIN_NAME: "protein",
    IMPORT_VITAMIN_A_DAILY_VALUE_NAME: "vitamin_a_daily_value",
    IMPORT_VITAMIN_C_DAILY_VALUE_NAME: "vitamin_c_daily_value",
    IMPORT_CALCIUM_NAME: "calcium_daily_value",
    IMPORT_IRON_DAILY_VALUE_NAME: "iron_daily_value",
}
